name: Count at-risk features in Discovery
on:
  push:
    branches:
      - main
      - test-actions
    paths:
      - 'data/input_2022/Discovery/Results/*.csv'

jobs:
  Count-at-risk-features-in-discovery:
    runs-on: ubuntu-latest
    steps:
      - name: Check out wot-testing
        uses: actions/checkout@v3

      - name: Check out wot-discovery
        uses: actions/checkout@v3
        with:
          repository: w3c/wot-discovery
          path: wot-discovery

      - name: Run assertion coverage script
        run: |
          python3 data/input_2022/scripts/discovery-coverage.py >> $GITHUB_STEP_SUMMARY
